// @flow

export const states = {
	ALL: `ALL`,
	INITIAL: `INITIAL`,
	REVIEW_READY: `REVIEW_READY`,
	AUDIT: `AUDIT`,
	LAUNCH_READY: `LAUNCH_READY`,
	ACTIVE: `ACTIVE`,
	COMPLETED: `COMPLETED`,
	SUCCESSFUL: `SUCCESSFUL`,
};
