export const companyCategories = [
	{ label: 'Agriculture', value: 1 },
	{ label: 'Big Data & Ai', value: 2 },
	{ label: 'Biotech and Medicine', value: 3 },
	{ label: 'Blockchain & Cryptocurrencies', value: 4 },
	{ label: 'Cyber Security', value: 5 },
	{ label: 'Design & Graphics', value: 6 },
	{ label: 'eCommerce', value: 7 },
	{ label: 'Education', value: 8 },
	{ label: 'Energy & Sustainability', value: 9 },
	{ label: 'Fashion', value: 10 },
	{ label: 'Financial Services', value: 11 },
	{ label: 'Food & Drinks', value: 12 },
	{ label: 'Gaming', value: 13 },
	{ label: 'Hardware', value: 14 },
	{ label: 'Health & Fitness', value: 15 },
	{ label: 'Human Resources', value: 16 },
	{ label: 'Insurance', value: 17 },
	{ label: 'IoT (The Internet of Things)', value: 18 },
	{ label: 'Legal Services', value: 19 },
	{ label: 'Marketing & Advertising', value: 20 },
	{ label: 'Media & Communication', value: 21 },
	{ label: 'Mobility & Logistics', value: 22 },
	{ label: 'Music', value: 23 },
	{ label: 'Real Estate', value: 24 },
	{
		label: 'Sharing & Gig Economy (Rent Services to the Companies)',
		value: 25,
	},
	{ label: 'Social Media & Events', value: 26 },
	{ label: 'Travel', value: 27 },
	{ label: 'Video & Photography', value: 28 },
	{ label: 'Virtual & Augmented Reality', value: 29 },
];
