export const paymentsStates = {
	ALL: `ALL`,
	PENDING: `PENDING`,
	INITIAL: `INITIAL`,
	OWNER_APPROVED: `OWNER_APPROVED`,
	OWNER_REJECTED: `OWNER_REJECTED`,
	AUDIT_APPROVED: `AUDIT_APPROVED`,
	AUDIT_REJECTED: `AUDIT_REJECTED`,
	PAID: `PAID`,
	EXPIRED: `EXPIRED`,
};
