// @flow

export const ROLE_ENTREPRENEUR = `ROLE_ENTREPRENEUR`;
export const ROLE_ADMIN = `ROLE_ADMIN`;
export const ROLE_COMPANY_INVESTOR = 'ROLE_COMPANY_INVESTOR';
export const ROLE_INDIVIDUAL_INVESTOR = 'ROLE_INDIVIDUAL_INVESTOR';
export const ROLE_CORPORATE_INVESTOR = `ROLE_CORPORATE_INVESTOR`;
